db:
    image: sameersbn/postgresql:9.4
    environment:
        - DB_USER=c4si
        - DB_PASS=password
        - DB_NAME=c4si
webapp:
    image: frenchbeard/c4si
    environment:
        - DB_USER=c4si
        - DB_PASS=password
        - DB_NAME=c4si
        - DB_HOST=db
        - APP_NAME=c4admin
    links:
        - db:db
nginx:
    image: frenchbeard/nginx
    links:
        - webapp:webapp
    ports:
        - "80:80"
    volumes_from:
        - webapp
